# Elezaio Installer Configuration

INSTALLER_NAME="Elezaio Installer"
INSTALLER_VERSION="1.0.0"
DISTRO_NAME="Elezaio Linux"
DISTRO_VERSION="2026.3r11"
DISTRO_CODENAME="Nova"
DISTRO_WEBSITE="https://elezaio-linux.github.io"
