#!/bin/bash
# Elezaio Installer - System Configuration
# All behavior driven by config.conf

_log() { echo "[$(date '+%H:%M:%S')] $*" >> "$LOG"; }

_chroot() {
    DEBIAN_FRONTEND=noninteractive \
    LANG=C \
    chroot "$MOUNT" /bin/bash -c "$*" >> "$LOG" 2>&1
}

# ── CONFIGURE ────────────────────────────────────────────────
core_configure() {
    _log "Configuring system"

    local root_uuid efi_uuid
    root_uuid=$(blkid -s UUID -o value "$ROOT_PART")
    efi_uuid=$(blkid -s UUID -o value "$EFI_PART")

    # fstab
    cat > "$MOUNT/etc/fstab" << FSTAB
# /etc/fstab - generated by Elezaio Installer
UUID=$root_uuid  /         ext4  errors=remount-ro,relatime  0  1
UUID=$efi_uuid   /boot/efi vfat  umask=0077,fmask=0077,dmask=0077  0  2
tmpfs            /tmp      tmpfs defaults,nosuid,nodev,noexec  0  0
FSTAB

    # Hostname
    echo "$SYSTEM_HOSTNAME" > "$MOUNT/etc/hostname"
    cat > "$MOUNT/etc/hosts" << HOSTS
127.0.0.1   localhost
127.0.1.1   $SYSTEM_HOSTNAME
::1         localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
HOSTS

    # Locale
    echo "LANG=$SYSTEM_LANG" > "$MOUNT/etc/locale.conf"
    echo "$SYSTEM_LANG UTF-8" > "$MOUNT/etc/locale.gen"
    echo "en_US.UTF-8 UTF-8" >> "$MOUNT/etc/locale.gen"

    # Keyboard - console
    cat > "$MOUNT/etc/vconsole.conf" << VCONSOLE
KEYMAP=$SYSTEM_KB
FONT=Lat2-Terminus16
VCONSOLE

    # Keyboard - X11/Wayland
    mkdir -p "$MOUNT/etc/X11/xorg.conf.d"
    cat > "$MOUNT/etc/X11/xorg.conf.d/00-keyboard.conf" << XKBD
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "$SYSTEM_KB"
EndSection
XKBD

    # APT sources
    echo "$APT_SOURCES" > "$MOUNT/etc/apt/sources.list"

    # Sysctl tweaks
    echo "$SYSCTL_TWEAKS" > "$MOUNT/etc/sysctl.d/99-elezaio.conf"

    # DNS via systemd-resolved
    mkdir -p "$MOUNT/etc/systemd/resolved.conf.d"
    cat > "$MOUNT/etc/systemd/resolved.conf.d/dns.conf" << DNS
[Resolve]
DNS=$DNS_PRIMARY $DNS_SECONDARY
FallbackDNS=$DNS_FALLBACK
DNSSEC=no
DNSOverTLS=no
DNS

    # Zram
    cat > "$MOUNT/etc/default/zramswap" << ZRAM
ALGO=$ZRAM_ALGO
PERCENT=$ZRAM_PERCENT
ZRAM

    # Remove live-specific kernel params from grub
    mkdir -p "$MOUNT/etc/default"
    cat > "$MOUNT/etc/default/grub" << GRUB
GRUB_DEFAULT=0
GRUB_TIMEOUT=$GRUB_TIMEOUT
GRUB_DISTRIBUTOR="$GRUB_DISTRIBUTOR"
GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL_INPUT=console
GRUB

    _log "System configured"
}

# ── PACKAGES ─────────────────────────────────────────────────
core_packages() {
    _log "Installing packages"

    # Update package lists
    _chroot "apt-get update -qq"

    # Install all groups from config
    local all_pkgs=""
    for group in \
        PACKAGES_COMPOSITOR PACKAGES_AUDIO PACKAGES_NETWORK \
        PACKAGES_LOGIN PACKAGES_PERFORMANCE PACKAGES_SHELL \
        PACKAGES_FONTS PACKAGES_APPS PACKAGES_THEME PACKAGES_EXTRA; do
        all_pkgs+=" ${!group:-}"
    done

    # Install with no-recommends to keep it lean
    _chroot "DEBIAN_FRONTEND=noninteractive apt-get install -y \
        --no-install-recommends \
        $all_pkgs"

    # Enable services
    for svc in ${SERVICES_ENABLE:-}; do
        _chroot "systemctl enable $svc" || true
    done

    # Disable unnecessary services
    for svc in ${SERVICES_DISABLE:-}; do
        _chroot "systemctl disable $svc" || true
    done

    _log "Packages installed"
}

# ── USERS ────────────────────────────────────────────────────
core_users() {
    _log "Creating user $SYSTEM_USER"

    # Remove live users
    _chroot "userdel -rf user 2>/dev/null; userdel -rf live 2>/dev/null; true"

    # Create user with zsh
    _chroot "useradd -m -s /usr/bin/zsh -G ${USER_GROUPS} $SYSTEM_USER"

    # Set passwords
    _chroot "echo '$SYSTEM_USER:$SYSTEM_PASS' | chpasswd"
    _chroot "echo 'root:$SYSTEM_PASS' | chpasswd"

    # Install oh-my-zsh (non-interactive)
    if chroot "$MOUNT" which curl &>/dev/null; then
        chroot "$MOUNT" su -c \
            'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended' \
            "$SYSTEM_USER" >> "$LOG" 2>&1 || true
    fi

    # zshrc additions
    cat >> "$MOUNT/home/$SYSTEM_USER/.zshrc" << 'ZSH'

# Elezaio defaults
export EDITOR=nano
fastfetch 2>/dev/null || true
ZSH

    # Login manager
    if [[ "${LOGIN_MANAGER:-sddm}" == "sddm" ]]; then
        mkdir -p "$MOUNT/etc/sddm.conf.d"
        cat > "$MOUNT/etc/sddm.conf.d/elezaio.conf" << SDDM
[Autologin]
User=$SYSTEM_USER
Session=${SESSION_NAME:-mango}

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_DISABLE_WINDOWDECORATION=1

[Theme]
Current=
SDDM
        _chroot "systemctl enable sddm"

    elif [[ "${LOGIN_MANAGER:-}" == "greetd" ]]; then
        mkdir -p "$MOUNT/etc/greetd"
        cat > "$MOUNT/etc/greetd/config.toml" << GREETD
[terminal]
vt = 1

[default_session]
command = "${SESSION_NAME:-mango}"
user = "$SYSTEM_USER"
GREETD
        _chroot "systemctl enable greetd"
    fi

    _chroot "systemctl set-default graphical.target"

    # Fix home ownership
    chroot "$MOUNT" chown -R "$SYSTEM_USER:$SYSTEM_USER" \
        "/home/$SYSTEM_USER" >> "$LOG" 2>&1

    _log "User $SYSTEM_USER created"
}

# ── BOOTLOADER ───────────────────────────────────────────────
core_bootloader() {
    _log "Installing bootloader"

    # Install grub + shim for secure boot compatibility
    _chroot "DEBIAN_FRONTEND=noninteractive apt-get install -y \
        --no-install-recommends \
        grub-efi-amd64 grub-efi-amd64-signed shim-signed"

    # Install to disk
    chroot "$MOUNT" grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id="${GRUB_BOOTLOADER_ID:-Elezaio}" \
        --recheck \
        --no-nvram \
        "$INSTALL_DISK" >> "$LOG" 2>&1

    # Also install removable fallback (for finicky UEFI firmware)
    chroot "$MOUNT" grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id="${GRUB_BOOTLOADER_ID:-Elezaio}" \
        --recheck \
        --removable \
        "$INSTALL_DISK" >> "$LOG" 2>&1

    # Regenerate initramfs BEFORE update-grub
    _log "Regenerating initramfs"
    _chroot "update-initramfs -u -k all"

    # Generate grub config
    _chroot "update-grub"

    _log "Bootloader installed"
}

# ── CLEANUP ──────────────────────────────────────────────────
core_cleanup() {
    _log "Cleaning up"

    # Generate locales
    _chroot "locale-gen"

    # Remove live-specific packages
    _chroot "DEBIAN_FRONTEND=noninteractive apt-get remove -y \
        ${LIVE_PACKAGES:-live-boot live-boot-initramfs-tools live-config live-config-systemd live-tools} \
        2>/dev/null; true"

    _chroot "apt-get autoremove -y"
    _chroot "apt-get clean"

    # Run optional post-install hook inside chroot
    if [[ -n "${POST_INSTALL_HOOK:-}" && -f "$POST_INSTALL_HOOK" ]]; then
        _log "Running post-install hook"
        cp "$POST_INSTALL_HOOK" "$MOUNT/tmp/post-install.sh"
        _chroot "bash /tmp/post-install.sh"
        rm -f "$MOUNT/tmp/post-install.sh"
    fi

    # Clean up live resolv.conf symlink and restore
    rm -f "$MOUNT/etc/resolv.conf"
    ln -sf /run/systemd/resolve/stub-resolv.conf \
        "$MOUNT/etc/resolv.conf" 2>/dev/null || true

    # Remove installer from installed system
    rm -rf "$MOUNT/usr/share/elezaio-installer" 2>/dev/null || true
    rm -rf "$MOUNT/tmp/"* 2>/dev/null || true

    _log "Cleanup complete"
}

# ── INSTALL ORCHESTRATOR ─────────────────────────────────────
core_install() {
    local start_time
    start_time=$(date +%s)
    : > "$LOG"
    _log "=== Elezaio Install Start ==="

    _smooth() {
        local from="$1" to="$2" msg="$3" duration="${4:-2}"
        local steps=$(( to - from ))
        [[ $steps -le 0 ]] && steps=1
        local delay
        delay=$(awk "BEGIN {printf \"%.3f\", $duration / $steps}")
        local i=$from
        while [[ $i -le $to ]]; do
            local elapsed=$(( $(date +%s) - start_time ))
            local eta="calculating..."
            if [[ $i -gt 2 && $elapsed -gt 0 ]]; then
                local total_est=$(( elapsed * 100 / (i + 1) ))
                local secs_left=$(( total_est - elapsed ))
                if [[ $secs_left -gt 60 ]]; then
                    eta="~$((secs_left/60))m $((secs_left%60))s"
                elif [[ $secs_left -gt 0 ]]; then
                    eta="${secs_left}s"
                else
                    eta="almost done"
                fi
            fi
            printf "XXX\n%d\n%s\n\nElapsed: %ds  |  ETA: %s\nXXX\n" \
                "$i" "$msg" "$elapsed" "$eta"
            sleep "$delay"
            (( i++ )) || true
        done
    }

    {
        _smooth 0 3 "Preparing disk..." 1
        core_partition || { _log "FAILED: core_partition"; exit 1; }

        _smooth 3 8 "Mounting partitions..." 1
        core_mount || { _log "FAILED: core_mount"; exit 1; }

        # Copy squashfs in background, track real progress
        core_copy &
        local copy_pid=$!

        local squashfs=""
        for path in \
            /lib/live/mount/medium/live/filesystem.squashfs \
            /run/live/medium/live/filesystem.squashfs; do
            [ -f "$path" ] && { squashfs="$path"; break; }
        done
        local total_size=0
        [[ -f "$squashfs" ]] && total_size=$(stat -c%s "$squashfs")
        local last_pct=8

        while kill -0 $copy_pid 2>/dev/null; do
            local elapsed=$(( $(date +%s) - start_time ))
            local written
            written=$(du -sb "$MOUNT" 2>/dev/null | awk '{print $1}' || echo 0)
            local pct=8
            [[ $total_size -gt 0 ]] && {
                pct=$(( 8 + (written * 47 / total_size) ))
                [[ $pct -gt 55 ]] && pct=55
            }
            if [[ $pct -gt $last_pct ]]; then
                local j=$last_pct
                while [[ $j -le $pct ]]; do
                    local el=$(( $(date +%s) - start_time ))
                    local eta="calculating..."
                    [[ $el -gt 0 && $j -gt 2 ]] && {
                        local te=$(( el * 100 / (j + 1) ))
                        local sl=$(( te - el ))
                        [[ $sl -gt 60 ]] && eta="~$((sl/60))m $((sl%60))s" || eta="${sl}s"
                    }
                    printf "XXX\n%d\nCopying system files...\n\nElapsed: %ds  |  ETA: %s\nXXX\n" \
                        "$j" "$el" "$eta"
                    sleep 0.05
                    (( j++ )) || true
                done
                last_pct=$pct
            fi
            sleep 1
        done
        wait $copy_pid || { _log "FAILED: core_copy"; exit 1; }

        _smooth $last_pct 58 "Configuring system..." 3
        core_configure || { _log "FAILED: core_configure"; exit 1; }

        # Bind virtual filesystems before chroot operations
        core_bind_mount || { _log "FAILED: core_bind_mount"; exit 1; }

        _smooth 58 76 "Installing packages..." 90
        core_packages || { _log "FAILED: core_packages"; exit 1; }

        _smooth 76 83 "Creating user $SYSTEM_USER..." 4
        core_users || { _log "FAILED: core_users"; exit 1; }

        _smooth 83 93 "Installing bootloader..." 6
        core_bootloader || { _log "FAILED: core_bootloader"; exit 1; }

        _smooth 93 98 "Cleaning up..." 4
        core_cleanup

        # Unbind virtual filesystems
        core_unbind

        _smooth 98 100 "Installation complete!" 1
        sleep 1

    } | whiptail \
        --title "  $INSTALLER_TITLE  " \
        --backtitle "$INSTALLER_VERSION \"$INSTALLER_CODENAME\"" \
        --gauge "Installing Elezaio Linux..." 10 70 0

    local exit_code=${PIPESTATUS[0]}
    if [[ $exit_code -ne 0 ]]; then
        whiptail --title "Installation Failed" \
            --textbox "$LOG" 20 70
        exit 1
    fi
}
