#!/bin/bash
# Elezaio Installer - System Configuration
# All behavior driven by config.conf

_log() { echo "[$(date '+%H:%M:%S')] $*" >> "$LOG"; }

_chroot() {
    DEBIAN_FRONTEND=noninteractive \
    LANG=C \
    chroot "$MOUNT" /bin/bash -c "$*" >> "$LOG" 2>&1
}

# ── CONFIGURE ────────────────────────────────────────────────
core_configure() {
    _log "Configuring system"

    local root_uuid efi_uuid
    root_uuid=$(blkid -s UUID -o value "$ROOT_PART")
    efi_uuid=$(blkid -s UUID -o value "$EFI_PART")

    cat > "$MOUNT/etc/fstab" << FSTAB
# /etc/fstab - generated by Elezaio Installer
UUID=$root_uuid  /         ext4  errors=remount-ro,relatime  0  1
UUID=$efi_uuid   /boot/efi vfat  umask=0077,fmask=0077,dmask=0077  0  2
tmpfs            /tmp      tmpfs defaults,nosuid,nodev,noexec  0  0
FSTAB

    echo "$SYSTEM_HOSTNAME" > "$MOUNT/etc/hostname"
    cat > "$MOUNT/etc/hosts" << HOSTS
127.0.0.1   localhost
127.0.1.1   $SYSTEM_HOSTNAME
::1         localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
HOSTS

    echo "LANG=$SYSTEM_LANG" > "$MOUNT/etc/locale.conf"
    echo "$SYSTEM_LANG UTF-8" > "$MOUNT/etc/locale.gen"
    echo "en_US.UTF-8 UTF-8" >> "$MOUNT/etc/locale.gen"

    cat > "$MOUNT/etc/vconsole.conf" << VCONSOLE
KEYMAP=$SYSTEM_KB
FONT=Lat2-Terminus16
VCONSOLE

    mkdir -p "$MOUNT/etc/X11/xorg.conf.d"
    cat > "$MOUNT/etc/X11/xorg.conf.d/00-keyboard.conf" << XKBD
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "$SYSTEM_KB"
EndSection
XKBD

    echo "$APT_SOURCES" > "$MOUNT/etc/apt/sources.list"
    echo "$SYSCTL_TWEAKS" > "$MOUNT/etc/sysctl.d/99-elezaio.conf"

    mkdir -p "$MOUNT/etc/systemd/resolved.conf.d"
    cat > "$MOUNT/etc/systemd/resolved.conf.d/dns.conf" << DNS
[Resolve]
DNS=$DNS_PRIMARY $DNS_SECONDARY
FallbackDNS=$DNS_FALLBACK
DNSSEC=no
DNSOverTLS=no
DNS

    cat > "$MOUNT/etc/default/zramswap" << ZRAM
ALGO=$ZRAM_ALGO
PERCENT=$ZRAM_PERCENT
ZRAM

    cat > "$MOUNT/etc/default/grub" << GRUB
GRUB_DEFAULT=0
GRUB_TIMEOUT=$GRUB_TIMEOUT
GRUB_DISTRIBUTOR="$GRUB_DISTRIBUTOR"
GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE"
GRUB_CMDLINE_LINUX=""
GRUB_TERMINAL_INPUT=console
GRUB

    _log "System configured"
}

# ── PACKAGES ─────────────────────────────────────────────────
core_packages() {
    _log "Installing packages"

    _chroot "apt-get update -qq"

    local all_pkgs=""
    for group in \
        PACKAGES_COMPOSITOR PACKAGES_AUDIO PACKAGES_NETWORK \
        PACKAGES_LOGIN PACKAGES_PERFORMANCE PACKAGES_SHELL \
        PACKAGES_FONTS PACKAGES_APPS PACKAGES_THEME PACKAGES_EXTRA; do
        all_pkgs+=" ${!group:-}"
    done

    _chroot "DEBIAN_FRONTEND=noninteractive apt-get install -y \
        --no-install-recommends \
        $all_pkgs"

    for svc in ${SERVICES_ENABLE:-}; do
        _chroot "systemctl enable $svc" || true
    done

    for svc in ${SERVICES_DISABLE:-}; do
        _chroot "systemctl disable $svc" || true
    done

    _log "Packages installed"
}

# ── USERS ────────────────────────────────────────────────────
core_users() {
    _log "Creating user $SYSTEM_USER"

    _chroot "userdel -rf user 2>/dev/null; userdel -rf live 2>/dev/null; true"
    _chroot "useradd -m -s /usr/bin/zsh -G ${USER_GROUPS} $SYSTEM_USER"
    _chroot "echo '$SYSTEM_USER:$SYSTEM_PASS' | chpasswd"
    _chroot "echo 'root:$SYSTEM_PASS' | chpasswd"

    # Set zsh as default for all users
    _chroot "chsh -s /usr/bin/zsh root"
    _chroot "sed -i 's|SHELL=/bin/bash|SHELL=/usr/bin/zsh|' /etc/default/useradd"

    # Install oh-my-zsh
    if chroot "$MOUNT" which curl &>/dev/null; then
        chroot "$MOUNT" su -c \
            'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended' \
            "$SYSTEM_USER" >> "$LOG" 2>&1 || true
    fi

    cat >> "$MOUNT/home/$SYSTEM_USER/.zshrc" << 'ZSH'

# Elezaio defaults
export EDITOR=nano
fastfetch 2>/dev/null || true
ZSH

    # Setup greetd
    mkdir -p "$MOUNT/etc/greetd"
    cat > "$MOUNT/etc/greetd/config.toml" << GREETD
[terminal]
vt = 1

[default_session]
command = "${SESSION_NAME:-mango}"
user = "$SYSTEM_USER"
GREETD

    _chroot "systemctl enable greetd"
    _chroot "systemctl set-default graphical.target"

    chroot "$MOUNT" chown -R "$SYSTEM_USER:$SYSTEM_USER" \
        "/home/$SYSTEM_USER" >> "$LOG" 2>&1

    _log "User $SYSTEM_USER created"
}

# ── BOOTLOADER ───────────────────────────────────────────────
core_bootloader() {
    _log "Installing bootloader"

    _chroot "DEBIAN_FRONTEND=noninteractive apt-get install -y \
        --no-install-recommends \
        grub-efi-amd64 grub-efi-amd64-signed shim-signed"

    chroot "$MOUNT" grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id="${GRUB_BOOTLOADER_ID:-Elezaio}" \
        --recheck \
        --no-nvram \
        "$INSTALL_DISK" >> "$LOG" 2>&1

    chroot "$MOUNT" grub-install \
        --target=x86_64-efi \
        --efi-directory=/boot/efi \
        --bootloader-id="${GRUB_BOOTLOADER_ID:-Elezaio}" \
        --recheck \
        --removable \
        "$INSTALL_DISK" >> "$LOG" 2>&1

    _log "Regenerating initramfs"
    _chroot "update-initramfs -u -k all"
    _chroot "update-grub"

    _log "Bootloader installed"
}

# ── CLEANUP ──────────────────────────────────────────────────
core_cleanup() {
    _log "Cleaning up"

    _chroot "locale-gen"

    _chroot "DEBIAN_FRONTEND=noninteractive apt-get remove -y \
        ${LIVE_PACKAGES:-live-boot live-boot-initramfs-tools live-config live-config-systemd live-tools} \
        2>/dev/null; true"

    _chroot "apt-get autoremove -y"
    _chroot "apt-get clean"

    if [[ -n "${POST_INSTALL_HOOK:-}" && -f "$POST_INSTALL_HOOK" ]]; then
        _log "Running post-install hook"
        cp "$POST_INSTALL_HOOK" "$MOUNT/tmp/post-install.sh"
        _chroot "bash /tmp/post-install.sh"
        rm -f "$MOUNT/tmp/post-install.sh"
    fi

    rm -f "$MOUNT/etc/resolv.conf"
    ln -sf /run/systemd/resolve/stub-resolv.conf \
        "$MOUNT/etc/resolv.conf" 2>/dev/null || true

    rm -rf "$MOUNT/usr/share/elezaio-installer" 2>/dev/null || true
    rm -rf "$MOUNT/tmp/"* 2>/dev/null || true

    _log "Cleanup complete"
}

# ── INSTALL ORCHESTRATOR ─────────────────────────────────────
core_install() {
    local start_time
    start_time=$(date +%s)
    : > "$LOG"
    _log "=== Elezaio Install Start ==="

    _step() {
        local msg="$1"; shift
        gum style --foreground "99" "  ⠋  $msg"
        "$@" >> "$LOG" 2>&1 || { _log "FAILED: $msg"; _show_error; exit 1; }
        gum style --foreground "2" "  ✓  $msg"
        _log "OK: $msg"
    }

    _show_error() {
        clear
        gum style \
            --foreground "160" --border rounded \
            --border-foreground "160" \
            --padding "1 4" --width 60 \
            "Installation Failed!\n\nCheck the log for details."
        gum pager < "$LOG"
    }

    clear
    gum style \
        --align center --width 60 \
        --padding "1 4" --border rounded \
        --border-foreground "99" --foreground "99" \
        "Installing Elezaio Linux $INSTALLER_VERSION"

    _step "Partitioning $INSTALL_DISK..." core_partition
    _step "Mounting partitions..." core_mount

    # Copy with real progress
    local squashfs=""
    for path in \
        /lib/live/mount/medium/live/filesystem.squashfs \
        /run/live/medium/live/filesystem.squashfs; do
        [ -f "$path" ] && { squashfs="$path"; break; }
    done

    if [ -n "$squashfs" ]; then
        local total_size
        total_size=$(stat -c%s "$squashfs")
        core_copy &
        local copy_pid=$!
        while kill -0 $copy_pid 2>/dev/null; do
            local written elapsed pct
            written=$(du -sb "$MOUNT" 2>/dev/null | awk '{print $1}' || echo 0)
            elapsed=$(( $(date +%s) - start_time ))
            pct=0
            [ "$total_size" -gt 0 ] && pct=$(( written * 100 / total_size ))
            printf "\r  Copying system files... %d%%  (elapsed: %ds)  " "$pct" "$elapsed"
            sleep 1
        done
        wait $copy_pid || { _log "FAILED: core_copy"; _show_error; exit 1; }
        echo ""
    else
        _step "Copying system files..." core_copy
    fi

    _step "Configuring system..." core_configure
    _step "Binding virtual filesystems..." core_bind_mount
    _step "Installing packages (this may take a while)..." core_packages
    _step "Creating user $SYSTEM_USER..." core_users
    _step "Installing bootloader..." core_bootloader
    _step "Cleaning up..." core_cleanup
    core_unbind

    local elapsed=$(( $(date +%s) - start_time ))
    clear
    gum style \
        --align center --width 60 \
        --padding "2 4" --border rounded \
        --border-foreground "99" --foreground "99" \
        "Installation Complete!\n\nFinished in ${elapsed}s"
}
